name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: build crates and examples (native-tls)
      run: |
        cargo build --workspace --all-targets --features native-tls
    - name: build crates and examples (rustls-tls)
      run: |
        cargo build --workspace --all-targets --no-default-features --features rustls-tls-webpki-roots
    - name: run clippy (native-tls)
      run: |
        cargo clippy --workspace --all-targets --features native-tls -- --deny clippy::all
    - name: run clippy (rustls-tls)
      run: |
        cargo clippy --workspace --all-targets --no-default-features --features rustls-tls-webpki-roots -- --deny clippy::all
    - name: install nextest
      uses: taiki-e/install-action@nextest
    - name: run unit tests
      run: cargo nextest run --retries 3 --no-tests=pass
